-- Definitions of memory structures that will be transmitted to the electron process

definitions = {
    Player = {{{"+PlayerState.PlayerNamePrivate", "+0"}, "s", 64},
            {{"++PlayerState.PawnPrivate", "+GPlayer.RootComponent", "+SceneComponent.RelativeLocation.X"}, "f"},
            {{"++PlayerState.PawnPrivate", "+GPlayer.RootComponent", "+SceneComponent.RelativeLocation.Y"}, "f"},
            {{"++PlayerState.PawnPrivate", "+GPlayer.RootComponent", "+SceneComponent.RelativeLocation.Z"}, "f"},
            {{"++PlayerState.PawnPrivate", "+GPlayer.RootComponent", "+SceneComponent.RelativeRotation.Pitch"}, "f"},
            {{"++PlayerState.PawnPrivate", "+GPlayer.RootComponent", "+SceneComponent.RelativeRotation.Yaw"}, "f"},
            {{"++PlayerState.PawnPrivate", "+GPlayer.RootComponent", "+SceneComponent.RelativeRotation.Roll"}, "f"}},
    PlayerMulti = {{{"+Character.myplayername", "+0"}, "s", 64},
            {{"+Character.RootComponent", "+SceneComponent.RelativeLocation.X"}, "f"},
            {{"+Character.RootComponent", "+SceneComponent.RelativeLocation.Y"}, "f"},
            {{"+Character.RootComponent", "+SceneComponent.RelativeLocation.Z"}, "f"},
            {{"+Character.RootComponent", "+SceneComponent.RelativeRotation.Pitch"}, "f"},
            {{"+Character.RootComponent", "+SceneComponent.RelativeRotation.Yaw"}, "f"},
            {{"+Character.RootComponent", "+SceneComponent.RelativeRotation.Roll"}, "f"}},
    FrameCar = {{{"+FrameCar.FrameType", "+0"}, "s", 64}, {{"+FrameCar.FrameName"}, "t", 64},
                {{"+FrameCar.FrameNumber", "+28", "+0"}, "s", 64},
                {{"+FrameCar.RootComponent", "+SceneComponent.RelativeLocation.X"}, "f"},
                {{"+FrameCar.RootComponent", "+SceneComponent.RelativeLocation.Y"}, "f"},
                {{"+FrameCar.RootComponent", "+SceneComponent.RelativeLocation.Z"}, "f"},
                {{"+FrameCar.RootComponent", "+SceneComponent.RelativeRotation.Pitch"}, "f"},
                {{"+FrameCar.RootComponent", "+SceneComponent.RelativeRotation.Yaw"}, "f"},
                {{"+FrameCar.RootComponent", "+SceneComponent.RelativeRotation.Roll"}, "f"},
                {{"+FrameCar.MyRegulator", "+Regulator.openPercentage"}, "f"},
                {{"+FrameCar.MyReverser", "+Reverser.forwardvalue"}, "f"},
                {{"+FrameCar.MyBrake", "+Brake.brakevalue"}, "f"}},
    Switch = {{{"+Switch.switchtype"}, "i"}, {{"+Switch.switchstate"}, "i"},
              {{"+Switch.RootComponent", "+SceneComponent.RelativeLocation.X"}, "f"},
              {{"+Switch.RootComponent", "+SceneComponent.RelativeLocation.Y"}, "f"},
              {{"+Switch.RootComponent", "+SceneComponent.RelativeLocation.Z"}, "f"},
              {{"+Switch.RootComponent", "+SceneComponent.RelativeRotation.Pitch"}, "f"},
              {{"+Switch.RootComponent", "+SceneComponent.RelativeRotation.Yaw"}, "f"},
              {{"+Switch.RootComponent", "+SceneComponent.RelativeRotation.Roll"}, "f"}},
    Turntable = {{{"+TurnTable.RootComponent", "+SceneComponent.RelativeLocation.X"}, "f"},
                 {{"+TurnTable.RootComponent", "+SceneComponent.RelativeLocation.Y"}, "f"},
                 {{"+TurnTable.RootComponent", "+SceneComponent.RelativeLocation.Z"}, "f"},
                 {{"+TurnTable.RootComponent", "+SceneComponent.RelativeRotation.Pitch"}, "f"},
                 {{"+TurnTable.RootComponent", "+SceneComponent.RelativeRotation.Yaw"}, "f"},
                 {{"+TurnTable.RootComponent", "+SceneComponent.RelativeRotation.Roll"}, "f"},
                 {{"+TurnTable.deckmesh", "+SceneComponent.RelativeRotation.Pitch"}, "f"},
                 {{"+TurnTable.deckmesh", "+SceneComponent.RelativeRotation.Yaw"}, "f"},
                 {{"+TurnTable.deckmesh", "+SceneComponent.RelativeRotation.Roll"}, "f"}},
    WaterTower = {{{"+WaterTower.RootComponent", "+SceneComponent.RelativeLocation.X"}, "f"},
                  {{"+WaterTower.RootComponent", "+SceneComponent.RelativeLocation.Y"}, "f"},
                  {{"+WaterTower.RootComponent", "+SceneComponent.RelativeLocation.Z"}, "f"},
                  {{"+WaterTower.RootComponent", "+SceneComponent.RelativeRotation.Pitch"}, "f"},
                  {{"+WaterTower.RootComponent", "+SceneComponent.RelativeRotation.Yaw"}, "f"},
                  {{"+WaterTower.RootComponent", "+SceneComponent.RelativeRotation.Roll"}, "f"}},
    Industry = {{{"+Industry.industrytype"}, "i"},
                {{"+Industry.RootComponent", "+SceneComponent.RelativeLocation.X"}, "f"},
                {{"+Industry.RootComponent", "+SceneComponent.RelativeLocation.Y"}, "f"},
                {{"+Industry.RootComponent", "+SceneComponent.RelativeLocation.Z"}, "f"},
                {{"+Industry.RootComponent", "+SceneComponent.RelativeRotation.Pitch"}, "f"},
                {{"+Industry.RootComponent", "+SceneComponent.RelativeRotation.Yaw"}, "f"},
                {{"+Industry.RootComponent", "+SceneComponent.RelativeRotation.Roll"}, "f"}},
    Spline = {{{"+Spline.SplineControlPoints_size"}},
                {{"+Spline.SplineControlPoints"}},
                {{"+Spline.SplineMeshBoolArray"}},
                {{"+Spline.SplineType"}}},
}

-- If an channel actor STARTS WITH a particular name, it will use the corresponding definition
channelNames = {
    BP_Player_Conductor = "PlayerMulti",
    BP_SplineActor = "Spline",
    BP_switch = "Switch",
    BP_watertower = "WaterTower",
    BP_industry = "Industry",
    BP_turntable = "Turntable",

    flatcar = "FrameCar", --flatcar_cordwood, flatcar_hopper, flatcar_logs, flatcar_stakes, flatcar_tanker
    boxcar = "FrameCar",
    class70 = "FrameCar", --class70, class70_tender
    climax = "FrameCar",
    cooke260 = "FrameCar", --cooke260, cooke260_updg_tender
    eureka = "FrameCar", --eureka, eureka_tender
    handcar = "FrameCar",
    heisler = "FrameCar",
    porter = "FrameCar" --porter040, porter042
}